### ISSUE TITLE
Exception While trying to redirect

### ISSUE THREAD

**Issue by balasubram** [hdiv/hdiv#39]
Whenever there is a redirect, I get the exception as given below. I recently did a 2.1.4 update. There were no errors in 2.1.4-SNAPSHOT. What can be the problem ?

Thanks & Regards 
Bala

[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:206) Exception in request validation:
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:206) Exception in request validation:
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:207) Message: Request has not been initialized in threadlocal
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:207) Message: Request has not been initialized in threadlocal
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:214) StackTrace:     at org.hdiv.util.HDIVUtil.getHttpServletRequest(HDIVUtil.java:349)
    at org.hdiv.util.HDIVUtil.getHttpSession(HDIVUtil.java:335)
    at org.hdiv.session.SessionHDIV.getHttpSession(SessionHDIV.java:303)
    at org.hdiv.session.SessionHDIV.addPage(SessionHDIV.java:129)
    at org.hdiv.dataComposer.DataComposerMemory.endPage(DataComposerMemory.java:515)
    at org.hdiv.filter.ValidatorHelperRequest.endPage(ValidatorHelperRequest.java:1008)
    at org.hdiv.filter.ValidatorFilter.processRequest(ValidatorFilter.java:258)
    at org.hdiv.filter.ValidatorFilter.doFilterInternal(ValidatorFilter.java:191)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:214) 
The exception Stacktrace is given below.

StackTrace:     at org.hdiv.util.HDIVUtil.getHttpServletRequest(HDIVUtil.java:349)
    at org.hdiv.util.HDIVUtil.getHttpSession(HDIVUtil.java:335)
    at org.hdiv.session.SessionHDIV.getHttpSession(SessionHDIV.java:303)
    at org.hdiv.session.SessionHDIV.addPage(SessionHDIV.java:129)
    at org.hdiv.dataComposer.DataComposerMemory.endPage(DataComposerMemory.java:515)
    at org.hdiv.filter.ValidatorHelperRequest.endPage(ValidatorHelperRequest.java:1008)
    at org.hdiv.filter.ValidatorFilter.processRequest(ValidatorFilter.java:258)
    at org.hdiv.filter.ValidatorFilter.doFilterInternal(ValidatorFilter.java:191)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:215) Cause: null
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:215) Cause: null
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:216) Exception: org.hdiv.exception.HDIVException: Request has not been initialized in threadlocal
[ERROR] [http-bio-7780-exec-3 03:01:51](ValidatorFilter.java:doFilterInternal:216) Exception: org.hdiv.exception.HDIVException: Request has not been initialized in threadlocal
Jul 30, 2013 3:01:51 PM org.apache.catalina.core.StandardWrapperValve invoke

ul 30, 2013 3:37:30 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [action] in context with path [/Sampe] threw exception
java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed
    at org.apache.catalina.connector.ResponseFacade.sendRedirect(ResponseFacade.java:483)
    at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:138)
    at org.springframework.security.web.firewall.FirewalledResponse.sendRedirect(FirewalledResponse.java:25)
    at org.hdiv.filter.ValidatorFilter.doFilterInternal(ValidatorFilter.java:220)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by nazskyhi** [comment]
is this issue still existing hdiv 2.1.4

**Comment by gillarramendi** [comment]
Check your config in web.xml file. It seems 'ValidatorFilter' is not processing the request.
It is mandatory to configure 'ValidatorFilter' for all requests in order to initialize HDIV for the request.

**Comment by nazskyhi** [comment]
Hi,
I have added the below given configuration in web.xml

<filter>
        <filter-name>ValidatorFilter</filter-name>
        <filter-class>org.hdiv.filter.ValidatorFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>ValidatorFilter</filter-name>
        <servlet-name>sample-servlet</servlet-name>
    </filter-mapping>
