### ISSUE TITLE
NullPointerException in org.hdiv.filter.ValidatorFilter

### ISSUE THREAD

**Issue by dillon-sellars** [hdiv/hdiv#45]
Just upgraded from 2.1.4 to 2.1.5. Getting this error on some requests during automated tests. 

java.lang.NullPointerException
        at org.hdiv.filter.ValidatorFilter.doFilterInternal(ValidatorFilter.java:128)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

**Comment by gillarramendi** [comment]
Reopen the issue if it continues in the last HDIV version.
Thanks
